import React, { useState } from 'react';
import { Heart, ShoppingCart, Eye, Star, Shirt, Trophy, Users } from 'lucide-react';

const SportsJerseyPage = () => {
  const [favorites, setFavorites] = useState(new Set());
  const [hoveredProduct, setHoveredProduct] = useState(null);
  const [selectedSize, setSelectedSize] = useState({});
  const [activeFilter, setActiveFilter] = useState('All');

  const products = [
    {
      id: 1,
      name: "Manchester United Home Jersey",
      originalPrice: 85000,
      salePrice: 65000,
      discount: 24,
      team: "Manchester United",
      season: "2024/25",
      type: "Home",
      sport: "Football",
      rating: 4.8,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Red', 'White'],
      category: "Premier League"
    },
    {
      id: 2,
      name: "Real Madrid Away Jersey",
      originalPrice: 90000,
      salePrice: 72000,
      discount: 20,
      team: "Real Madrid",
      season: "2024/25",
      type: "Away",
      sport: "Football",
      rating: 4.9,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Black', 'Gold'],
      category: "La Liga"
    },
    {
      id: 3,
      name: "Barcelona Home Jersey",
      originalPrice: 88000,
      salePrice: 55000,
      discount: 38,
      team: "Barcelona",
      season: "2024/25",
      type: "Home",
      sport: "Football",
      rating: 4.7,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Blue', 'Red'],
      category: "La Liga"
    },
    {
      id: 4,
      name: "Lakers Home Jersey",
      originalPrice: 95000,
      salePrice: 76000,
      discount: 20,
      team: "Los Angeles Lakers",
      season: "2024/25",
      type: "Home",
      sport: "Basketball",
      rating: 4.6,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Purple', 'Gold'],
      category: "NBA"
    },
    {
      id: 5,
      name: "PSG Third Jersey",
      originalPrice: 82000,
      salePrice: 65000,
      discount: 21,
      team: "Paris Saint-Germain",
      season: "2024/25",
      type: "Third",
      sport: "Football",
      rating: 4.5,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Pink', 'Black'],
      category: "Ligue 1"
    },
    {
      id: 6,
      name: "Golden State Warriors Away",
      originalPrice: 92000,
      salePrice: 73000,
      discount: 21,
      team: "Golden State Warriors",
      season: "2024/25",
      type: "Away",
      sport: "Basketball",
      rating: 4.8,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Blue', 'Yellow'],
      category: "NBA"
    },
    {
      id: 7,
      name: "Arsenal Home Jersey",
      originalPrice: 86000,
      salePrice: 69000,
      discount: 20,
      team: "Arsenal",
      season: "2024/25",
      type: "Home",
      sport: "Football",
      rating: 4.7,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Red', 'White'],
      category: "Premier League"
    },
    {
      id: 8,
      name: "Chelsea Away Jersey",
      originalPrice: 84000,
      salePrice: 58000,
      discount: 31,
      team: "Chelsea",
      season: "2024/25",
      type: "Away",
      sport: "Football",
      rating: 4.4,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Orange', 'Blue'],
      category: "Premier League"
    },
    {
      id: 9,
      name: "Miami Heat Vice Jersey",
      originalPrice: 98000,
      salePrice: 78000,
      discount: 20,
      team: "Miami Heat",
      season: "2024/25",
      type: "City Edition",
      sport: "Basketball",
      rating: 4.9,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Pink', 'Blue'],
      category: "NBA"
    },
    {
      id: 10,
      name: "Liverpool Third Jersey",
      originalPrice: 87000,
      salePrice: 70000,
      discount: 20,
      team: "Liverpool",
      season: "2024/25",
      type: "Third",
      sport: "Football",
      rating: 4.6,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Green', 'Gold'],
      category: "Premier League"
    },
    {
      id: 11,
      name: "AC Milan Home Jersey",
      originalPrice: 83000,
      salePrice: 66000,
      discount: 20,
      team: "AC Milan",
      season: "2024/25",
      type: "Home",
      sport: "Football",
      rating: 4.5,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Red', 'Black'],
      category: "Serie A"
    },
    {
      id: 12,
      name: "Boston Celtics Home Jersey",
      originalPrice: 94000,
      salePrice: 75000,
      discount: 20,
      team: "Boston Celtics",
      season: "2024/25",
      type: "Home",
      sport: "Basketball",
      rating: 4.7,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Green', 'White'],
      category: "NBA"
    }
  ];
